resilence4j:
  retry:
    instances:
      inventoryServiceRetry:
        maxRetryAttempts: 3
        waitDuration: 5s
  ratelimiter:
    instances:
      inventoryServiceRateLimiter:
        limitRefreshPeriod: 5s
        limitForPeriod: 1
        timeoutDuration: 1s
  circuitbreaker:
    instances:
      inventoryCircuitBreaker:
        registerHealthIndicator: true
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 10
        minimumNumberOfCalls: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 20s
        permittedNumberOfCallsInHalfOpenState: 3
        eventConsumerBufferSize: 10

management:
  health:
    circuitbreaker:
      enable: true
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always